
-- Create messages table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    message TEXT NOT NULL
);

-- Create requests table
CREATE TABLE IF NOT EXISTS public.requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
    product_name TEXT NOT NULL,
    contact_info TEXT NOT NULL
);

-- Create admin_settings table for custom auth
CREATE TABLE IF NOT EXISTS public.admin_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password TEXT NOT NULL
);

-- Insert default admin user if not exists
INSERT INTO public.admin_settings (id, username, password)
VALUES (1, 'admin', 'password')
ON CONFLICT (id) DO NOTHING;

-- Enable Row Level Security (RLS)
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;

-- DROP EXISTING POLICIES TO PREVENT ERRORS
DROP POLICY IF EXISTS "Enable insert for all users" ON public.messages;
DROP POLICY IF EXISTS "Enable insert for all users" ON public.requests;
DROP POLICY IF EXISTS "Enable read access for authenticated users only" ON public.messages;
DROP POLICY IF EXISTS "Enable read access for authenticated users only" ON public.requests;
DROP POLICY IF EXISTS "Enable read for all users" ON public.messages;
DROP POLICY IF EXISTS "Enable read for all users" ON public.requests;
DROP POLICY IF EXISTS "Enable delete for all users" ON public.messages;
DROP POLICY IF EXISTS "Enable delete for all users" ON public.requests;
DROP POLICY IF EXISTS "Enable read for all users" ON public.admin_settings;
DROP POLICY IF EXISTS "Enable update for all users" ON public.admin_settings;


-- RE-CREATE POLICIES correct for Custom Auth ---

-- 1. Messages & Requests: Allow anyone to INSERT (public submission)
CREATE POLICY "Enable insert for all users" ON public.messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for all users" ON public.requests FOR INSERT WITH CHECK (true);

-- 2. Messages & Requests: Allow anyone to SELECT 
-- (Required because Admin panel doesn't use Supabase Auth)
CREATE POLICY "Enable read for all users" ON public.messages FOR SELECT USING (true);
CREATE POLICY "Enable read for all users" ON public.requests FOR SELECT USING (true);

-- 3. Messages & Requests: Allow anyone to DELETE (protected by client-side admin check)
CREATE POLICY "Enable delete for all users" ON public.messages FOR DELETE USING (true);
CREATE POLICY "Enable delete for all users" ON public.requests FOR DELETE USING (true);

-- 4. Admin Settings: Allow read access so AdminLogin.tsx can check credentials
CREATE POLICY "Enable read for all users" ON public.admin_settings FOR SELECT USING (true);

-- 5. Admin Settings: Allow update (for changing password)
CREATE POLICY "Enable update for all users" ON public.admin_settings FOR UPDATE USING (true);
